# Descriptive Analysis on Churn Data

**Purpose:** Summarize and visualize the main characteristics of the data to understand distributions and key patterns.

This file contains descriptive analysis to uncover facts about the data and its components, list of task to do:
1. Summary statistics for numerical features (mean, std, min, max, 25th, 50th, 75th percentiles).
2. Histograms, boxplots, and density plots to inspect the distribution of individual features.
3. Count plots for categorical variables (frequencies of each category).
4. Correlation matrix (using heatmap) to understand relationships between numerical variables.
5. Pairwise scatter plots to inspect pairwise relationships between features.

In [36]:
# importing necessary libraries
import os
import re
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings("ignore")

In [2]:
# lading the data
file_path = r"D:\Doccuments\GitHub\End-to-End-MLOps-Platform\data\raw\telecom_churn_data.csv"
df = pd.read_csv(file_path)

In [3]:
# creating data copy
data = df.copy()
data.head()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,last_date_of_month_9,arpu_6,arpu_7,arpu_8,arpu_9,onnet_mou_6,onnet_mou_7,onnet_mou_8,onnet_mou_9,offnet_mou_6,offnet_mou_7,offnet_mou_8,offnet_mou_9,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8,roam_ic_mou_9,roam_og_mou_6,roam_og_mou_7,roam_og_mou_8,roam_og_mou_9,loc_og_t2t_mou_6,loc_og_t2t_mou_7,loc_og_t2t_mou_8,loc_og_t2t_mou_9,loc_og_t2m_mou_6,loc_og_t2m_mou_7,loc_og_t2m_mou_8,loc_og_t2m_mou_9,loc_og_t2f_mou_6,loc_og_t2f_mou_7,loc_og_t2f_mou_8,loc_og_t2f_mou_9,loc_og_t2c_mou_6,loc_og_t2c_mou_7,loc_og_t2c_mou_8,loc_og_t2c_mou_9,loc_og_mou_6,loc_og_mou_7,loc_og_mou_8,loc_og_mou_9,std_og_t2t_mou_6,std_og_t2t_mou_7,std_og_t2t_mou_8,std_og_t2t_mou_9,std_og_t2m_mou_6,std_og_t2m_mou_7,std_og_t2m_mou_8,std_og_t2m_mou_9,std_og_t2f_mou_6,std_og_t2f_mou_7,std_og_t2f_mou_8,std_og_t2f_mou_9,std_og_t2c_mou_6,std_og_t2c_mou_7,std_og_t2c_mou_8,std_og_t2c_mou_9,std_og_mou_6,std_og_mou_7,std_og_mou_8,std_og_mou_9,isd_og_mou_6,isd_og_mou_7,isd_og_mou_8,isd_og_mou_9,spl_og_mou_6,spl_og_mou_7,spl_og_mou_8,spl_og_mou_9,og_others_6,og_others_7,og_others_8,og_others_9,total_og_mou_6,total_og_mou_7,total_og_mou_8,total_og_mou_9,loc_ic_t2t_mou_6,loc_ic_t2t_mou_7,loc_ic_t2t_mou_8,loc_ic_t2t_mou_9,loc_ic_t2m_mou_6,loc_ic_t2m_mou_7,loc_ic_t2m_mou_8,loc_ic_t2m_mou_9,loc_ic_t2f_mou_6,loc_ic_t2f_mou_7,loc_ic_t2f_mou_8,loc_ic_t2f_mou_9,loc_ic_mou_6,loc_ic_mou_7,loc_ic_mou_8,loc_ic_mou_9,std_ic_t2t_mou_6,std_ic_t2t_mou_7,std_ic_t2t_mou_8,std_ic_t2t_mou_9,std_ic_t2m_mou_6,std_ic_t2m_mou_7,std_ic_t2m_mou_8,std_ic_t2m_mou_9,std_ic_t2f_mou_6,std_ic_t2f_mou_7,std_ic_t2f_mou_8,std_ic_t2f_mou_9,std_ic_t2o_mou_6,std_ic_t2o_mou_7,std_ic_t2o_mou_8,std_ic_t2o_mou_9,std_ic_mou_6,std_ic_mou_7,std_ic_mou_8,std_ic_mou_9,total_ic_mou_6,total_ic_mou_7,total_ic_mou_8,total_ic_mou_9,spl_ic_mou_6,spl_ic_mou_7,spl_ic_mou_8,spl_ic_mou_9,isd_ic_mou_6,isd_ic_mou_7,isd_ic_mou_8,isd_ic_mou_9,ic_others_6,ic_others_7,ic_others_8,ic_others_9,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_num_9,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,total_rech_amt_9,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,max_rech_amt_9,date_of_last_rech_6,date_of_last_rech_7,date_of_last_rech_8,date_of_last_rech_9,last_day_rch_amt_6,last_day_rch_amt_7,last_day_rch_amt_8,last_day_rch_amt_9,date_of_last_rech_data_6,date_of_last_rech_data_7,date_of_last_rech_data_8,date_of_last_rech_data_9,total_rech_data_6,total_rech_data_7,total_rech_data_8,total_rech_data_9,max_rech_data_6,max_rech_data_7,max_rech_data_8,max_rech_data_9,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_2g_9,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,count_rech_3g_9,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,av_rech_amt_data_9,vol_2g_mb_6,vol_2g_mb_7,vol_2g_mb_8,vol_2g_mb_9,vol_3g_mb_6,vol_3g_mb_7,vol_3g_mb_8,vol_3g_mb_9,arpu_3g_6,arpu_3g_7,arpu_3g_8,arpu_3g_9,arpu_2g_6,arpu_2g_7,arpu_2g_8,arpu_2g_9,night_pck_user_6,night_pck_user_7,night_pck_user_8,night_pck_user_9,monthly_2g_6,monthly_2g_7,monthly_2g_8,monthly_2g_9,sachet_2g_6,sachet_2g_7,sachet_2g_8,sachet_2g_9,monthly_3g_6,monthly_3g_7,monthly_3g_8,monthly_3g_9,sachet_3g_6,sachet_3g_7,sachet_3g_8,sachet_3g_9,fb_user_6,fb_user_7,fb_user_8,fb_user_9,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g,sep_vbc_3g
0,7000842753,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,197.385,214.816,213.803,21.100,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.0,NaN,0.00,0.00,0.00,0.00,NaN,NaN,0.16,NaN,NaN,NaN,4.13,NaN,NaN,NaN,1.15,NaN,NaN,NaN,5.44,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.00,NaN,0.00,0.00,5.44,0.00,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,4,3,2,6,362,252,252,0,252,252,252,0,6/21/2014,7/16/2014,8/8/2014,9/28/2014,252,252,252,0,6/21/2014,7/16/2014,8/8/2014,NaN,1.0,1.0,1.0,NaN,252.0,252.0,252.0,NaN,0.0,0.0,0.0,NaN,1.0,1.0,1.0,NaN,252.0,252.0,252.0,NaN,30.13,1.32,5.75,0.0,83.57,150.76,109.61,0.00,212.17,212.17,212.17,NaN,212.17,212.17,212.17,NaN,0.0,0.0,0.0,NaN,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,1.0,1.0,1.0,NaN,968,30.4,0.0,101.20,3.58
1,7001865778,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,34.047,355.074,268.321,86.285,24.11,78.68,7.68,18.34,15.74,99.84,304.76,53.76,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,23.88,74.56,7.68,18.34,11.51,75.94,291.86,53.76,0.00,0.00,0.00,0.00,0.0,2.91,0.00,0.00,35.39,150.51,299.54,72.11,0.23,4.11,0.00,0.00,0.00,0.46,0.13,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.23,4.58,0.13,0.00,0.0,0.0,0.0,0.0,4.68,23.43,12.76,0.00,0.00,0.0,0.0,0.0,40.31,178.53,312.44,72.11,1.61,29.91,29.23,116.09,17.48,65.38,375.58,56.93,0.00,8.93,3.61,0.00,19.09,104.23,408.43,173.03,0.00,0.00,2.35,0.00,5.90,0.00,12.49,15.01,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,5.90,0.00,14.84,15.01,26.83,104.23,423.28,188.04,0.00,0.0,0.0,0.00,1.83,0.00,0.0,0.00,0.00,0.00,0.0,0.00,4,9,11,5,74,384,283,121,44,154,65,50,6/29/2014,7/31/2014,8/28/2014,9/30/2014,44,23,30,0,NaN,7/25/2014,8/10/2014,NaN,NaN,1.0,2.0,NaN,NaN,154.0,25.0,NaN,NaN,1.0,2.0,NaN,NaN,0.0,0.0,NaN,NaN,154.0,50.0,NaN,0.00,108.07,365.47,0.0,0.00,0.00,0.00,0.00,NaN,0.00,0.00,NaN,NaN,28.61,7.60,NaN,NaN,0.0,0.0,NaN,0,1,0,0,0,0,2,0,0,0,0,0,0,0,0,0,NaN,1.0,1.0,NaN,1006,0.0,0.0,0.00,0.00
2,7001625959,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,167.690,189.058,210.226,290.714,11.54,55.24,37.26,74.81,143.33,220.59,208.36,118.91,0.0,0.00,0.00,38.49,0.0,0.00,0.00,70.94,7.19,28.74,13.58,14.39,29.34,16.86,38.46,28.16,24.11,21.79,15.61,22.24,0.0,135.54,45.76,0.48,60.66,67.41,67.66,64.81,4.34,26.49,22.58,8.76,41.81,67.41,75.53,9.28,1.48,14.76,22.83,0.0,0.0,0.0,0.0,0.0,47.64,108.68,120.94,18.04,0.0,0.0,0.0,0.0,46.56,236.84,96.84,42.08,0.45,0.0,0.0,0.0,155.33,412.94,285.46,124.94,115.69,71.11,67.46,148.23,14.38,15.44,38.89,38.98,99.48,122.29,49.63,158.19,229.56,208.86,155.99,345.41,72.41,71.29,28.69,49.44,45.18,177.01,167.09,118.18,21.73,58.34,43.23,3.86,0.0,0.0,0.0,0.0,139.33,306.66,239.03,171.49,370.04,519.53,395.03,517.74,0.21,0.0,0.0,0.45,0.00,0.85,0.0,0.01,0.93,3.14,0.0,0.36,5,4,2,7,168,315,116,358,86,200,86,100,6/17/2014,7/24/2014,8/14/2014,9/29/2014,0,200,86,0,NaN,NaN,NaN,9/17/2014,NaN,NaN,NaN,1.0,NaN,NaN,NaN,46.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,46.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,8.42,NaN,NaN,NaN,2.84,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1.0,1103,0.0,0.0,4.17,0.00
3,7001204172,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,221.338,251.102,508.054,389.500,99.91,54.39,310.98,241.71,123.31,109.01,71.68,113.54,0.0,54.86,44.38,0.00,0.0,28.09,39.04,0.00,73.68,34.81,10.61,15.49,107.43,83.21,22.46,65.46,1.91,0.65,4.91,2.06,0.0,0.00,0.00,0.00,183.03,118.68,37.99,83.03,26.23,14.89,289.58,226.21,2.99,1.73,6.53,9.99,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,29.23,16.63,296.11,236.21,0.0,0.0,0.0,0.0,10.96,0.00,18.09,43.29,0.00,0.0,0.0,0.0,223.23,135.31,352.21,362.54,62.08,19.98,8.04,41.73,113.96,64.51,20.28,52.86,57.43,27.09,19.84,65.59,233.48,111.59,48.18,160.19,43.48,66.44,0.00,129.84,1.33,38.56,4.94,13.98,1.18,0.00,0.00,0.00,0.0,0.0,0.0,0.0,45.99,105.01,4.94,143.83,280.08,216.61,53.13,305.38,0.59,0.0,0.0,0.55,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0.80,10,11,18,14,230,310,601,410,60,50,50,50,6/28/2014,7/31/2014,8/31/2014,9/30/2014,30,50,50,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,2491,0.0,0.0,0.00,0.00
4,7000142493,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,261.636,309.876,238.174,163.426,50.31,149.44,83.89,58.78,76.96,91.88,124.26,45.81,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,50.31,149.44,83.89,58.78,67.64,91.88,124.26,37.89,0.00,0.00,0.00,1.93,0.0,0.00,0.00,0.00,117.96,241.33,208.16,98.61,0.00,0.00,0.00,0.00,9.31,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,9.31,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,5.98,0.00,0.0,0.0,0.0,127.28,241.33,208.16,104.59,105.68,88.49,233.81,154.56,106.84,109.54,104.13,48.24,1.50,0.00,0.00,0.00,214.03,198.04,337.94,202.81,0.00,0.00,0.86,2.31,1.93,0.25,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,1.93,0.25,0.86,2.31,216.44,198.29,338.81,205.31,0.00,0.0,0.0,0.18,0.00,0.00,0.0,0.00,0.48,0.00,0.0,0.00,5,6,3,4,196,350,287,200,56,110,110,50,6/26/2014,7/28/2014,8/9/2014,9/28/2014,50,110,110,50,6/4/2014,NaN,NaN,NaN,1.0,NaN,NaN,NaN,56.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,56.0,NaN,NaN,NaN,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0.0,NaN,NaN,NaN,1526,0.0,0.0,0.00,0.00

In [4]:
data.select_dtypes(float).describe().T

,count,mean,std,min,25%,50%,75%,max
loc_og_t2o_mou,98981.0,0.000000,0.000000,0.000,0.0000,0.000,0.0000,0.000
std_og_t2o_mou,98981.0,0.000000,0.000000,0.000,0.0000,0.000,0.0000,0.000
loc_ic_t2o_mou,98981.0,0.000000,0.000000,0.000,0.0000,0.000,0.0000,0.000
arpu_6,99999.0,282.987358,328.439770,-2258.709,93.4115,197.704,371.0600,27731.088
arpu_7,99999.0,278.536648,338.156291,-2014.045,86.9805,191.640,365.3445,35145.834
...,...,...,...,...,...,...,...,...
fb_user_9,25922.0,0.860968,0.345987,0.000,1.0000,1.000,1.0000,1.000
aug_vbc_3g,99999.0,68.170248,267.580450,0.000,0.0000,0.000,0.0000,12916.220
jul_vbc_3g,99999.0,66.839062,271.201856,0.000,0.0000,0.000,0.0000,9165.600
jun_vbc_3g,99999.0,60.021204,253.938223,0.000,0.0000,0.000,0.0000,11166.210
sep_vbc_3g,99999.0,3.299373,32.408353,0.000,0.0000,0.000,0.0000,2618.570

In [5]:
data.select_dtypes(int).describe().T

,count,mean,std,min,25%,50%,75%,max
mobile_number,99999.0,7.001207e+09,695669.386290,7.000000e+09,7.000606e+09,7.001205e+09,7.001812e+09,7.002411e+09
circle_id,99999.0,1.090000e+02,0.000000,1.090000e+02,1.090000e+02,1.090000e+02,1.090000e+02,1.090000e+02
total_rech_num_6,99999.0,7.558806e+00,7.078405,0.000000e+00,3.000000e+00,6.000000e+00,9.000000e+00,3.070000e+02
total_rech_num_7,99999.0,7.700367e+00,7.070422,0.000000e+00,3.000000e+00,6.000000e+00,1.000000e+01,1.380000e+02
total_rech_num_8,99999.0,7.212912e+00,7.203753,0.000000e+00,3.000000e+00,5.000000e+00,9.000000e+00,1.960000e+02
total_rech_num_9,99999.0,6.893019e+00,7.096261,0.000000e+00,3.000000e+00,5.000000e+00,9.000000e+00,1.310000e+02
total_rech_amt_6,99999.0,3.275146e+02,398.019701,0.000000e+00,1.090000e+02,2.300000e+02,4.375000e+02,3.519000e+04
total_rech_amt_7,99999.0,3.229630e+02,408.114237,0.000000e+00,1.000000e+02,2.200000e+02,4.280000e+02,4.033500e+04
total_rech_amt_8,99999.0,3.241571e+02,416.540455,0.000000e+00,9.000000e+01,2.250000e+02,4.345000e+02,4.532000e+04
total_rech_amt_9,99999.0,3.033457e+02,404.588583,0.000000e+00,5.200000e+01,2.000000e+02,4.150000e+02,3.723500e+04
max_rech_amt_6,99999.0,1.046375e+02,120.614894,0.000000e+00,3.000000e+01,1.100000e+02,1.200000e+02,4.010000e+03
max_rech_amt_7,99999.0,1.047524e+02,124.523970,0.000000e+00,3.000000e+01,1.100000e+02,1.280000e+02,4.010000e+03
max_rech_amt_8,99999.0,1.077282e+02,126.902505,0.000000e+00,3.000000e+01,9.800000e+01,1.440000e+02,4.449000e+03
max_rech_amt_9,99999.0,1.019439e+02,125.375109,0.000000e+00,2.800000e+01,6.100000e+01,1.440000e+02,3.399000e+03
last_day_rch_amt_6,99999.0,6.315625e+01,97.356649,0.000000e+00,0.000000e+00,3.000000e+01,1.100000e+02,4.010000e+03
last_day_rch_amt_7,99999.0,5.938580e+01,95.915385,0.000000e+00,0.000000e+00,3.000000e+01,1.100000e+02,4.010000e+03
last_day_rch_amt_8,99999.0,6.264172e+01,104.431816,0.000000e+00,0.000000e+00,3.000000e+01,1.300000e+02,4.449000e+03
last_day_rch_amt_9,99999.0,4.390125e+01,90.809712,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+01,3.399000e+03
monthly_2g_6,99999.0,7.964080e-02,0.295058,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
monthly_2g_7,99999.0,8.322083e-02,0.304395,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00
monthly_2g_8,99999.0,8.100081e-02,0.299568,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00
monthly_2g_9,99999.0,6.878069e-02,0.278120,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
sachet_2g_6,99999.0,3.893839e-01,1.497320,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.200000e+01
sachet_2g_7,99999.0,4.396344e-01,1.636230,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.800000e+01
sachet_2g_8,99999.0,4.500745e-01,1.630263,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.400000e+01
sachet_2g_9,99999.0,3.931039e-01,1.347140,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+01
monthly_3g_6,99999.0,7.592076e-02,0.363371,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.400000e+01
monthly_3g_7,99999.0,7.858079e-02,0.387231,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.600000e+01
monthly_3g_8,99999.0,8.294083e-02,0.384947,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.600000e+01
monthly_3g_9,99999.0,8.634086e-02,0.384978,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.100000e+01
sachet_3g_6,99999.0,7.478075e-02,0.568344,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.900000e+01
sachet_3g_7,99999.0,8.040080e-02,0.628334,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.500000e+01
sachet_3g_8,99999.0,8.450085e-02,0.660234,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.100000e+01
sachet_3g_9,99999.0,8.458085e-02,0.650457,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.900000e+01
aon,99999.0,1.219855e+03,954.733842,1.800000e+02,4.670000e+02,8.630000e+02,1.807500e+03,4.337000e+03

In [6]:
data.select_dtypes(object).describe().T

                          count unique        top   freq
last_date_of_month_6      99999      1  6/30/2014  99999
last_date_of_month_7      99398      1  7/31/2014  99398
last_date_of_month_8      98899      1  8/31/2014  98899
last_date_of_month_9      98340      1  9/30/2014  98340
date_of_last_rech_6       98392     30  6/30/2014  16960
date_of_last_rech_7       98232     31  7/31/2014  17288
date_of_last_rech_8       96377     31  8/31/2014  14706
date_of_last_rech_9       95239     30  9/29/2014  22623
date_of_last_rech_data_6  25153     30  6/30/2014   1888
date_of_last_rech_data_7  25571     31  7/31/2014   1813
date_of_last_rech_data_8  26339     31  8/31/2014   1998
date_of_last_rech_data_9  25922     30  9/29/2014   2329

Insights: 
- There are columns which have all values as 0 like, `loc_og_t2o_mou`, `std_og_t2o_mou`, `loc_ic_t2o_mou` need to remove these redundant columns
- There are many columns with outliers
- Data have **null values** and most of them are present in **object datatype** columns
- Integer value columns might also be continous rather than sparse.
- Object datatype columns are date columns.
- Columns: `last_date_of_month_6`, `last_date_of_month_7`, `last_date_of_month_8`, `last_date_of_month_9` are not informative as they only give us the last date of month.

In [7]:
# lets drop the last_date_of_month_*n columns
drop_cols = ["last_date_of_month_6", "last_date_of_month_7", "last_date_of_month_8", "last_date_of_month_9"]
data.drop(columns = drop_cols, inplace = True)
data.shape

(99999, 222)

In [8]:
# creating a function to get the column name where there is only one value present
def get_col_with_one_val(data:pd.DataFrame)->tuple:
    return tuple(i for i in data.columns if data[i].nunique()<=1)

cols_with_one_vals = get_col_with_one_val(data)

In [9]:
for i in cols_with_one_vals:
    print(f"Value in {i}: {data[i].unique()}")

Value in circle_id: [109]
Value in loc_og_t2o_mou: [ 0. nan]
Value in std_og_t2o_mou: [ 0. nan]
Value in loc_ic_t2o_mou: [ 0. nan]
Value in std_og_t2c_mou_6: [nan  0.]
Value in std_og_t2c_mou_7: [nan  0.]
Value in std_og_t2c_mou_8: [ 0. nan]
Value in std_og_t2c_mou_9: [nan  0.]
Value in std_ic_t2o_mou_6: [nan  0.]
Value in std_ic_t2o_mou_7: [nan  0.]
Value in std_ic_t2o_mou_8: [ 0. nan]
Value in std_ic_t2o_mou_9: [nan  0.]

We can drop these columns and it eill also help in removing the null values too.

In [10]:
drop_cols.extend(cols_with_one_vals)
data.drop(columns = list(cols_with_one_vals), inplace=True)
data.shape

(99999, 210)

### Univariate Analysis

In [11]:
# Making a seprate directory for storing plots
path = os.getcwd()
plots_dir = os.path.join(path, "plots")
univar_dir = os.path.join(plots_dir, "univariate_plots")

os.makedirs(plots_dir, exist_ok = True)
print(f"Directory created: {plots_dir}")

os.makedirs(univar_dir, exist_ok = True)
print(f"Directory created: {univar_dir}")

Directory created: d:\Doccuments\GitHub\End-to-End-MLOps-Platform\notebooks\Telecom_Churn_Data\plots
Directory created: d:\Doccuments\GitHub\End-to-End-MLOps-Platform\notebooks\Telecom_Churn_Data\plots\univariate_plots

In [22]:
non_null_cols = [col for col in data.columns if data[col].isna().sum()!=0]
print("Count of non null columns: ",len(non_null_cols))

Count of non null columns:  152

In [23]:
nn_nuniq_10less = {col:data[col].nunique() for col in non_null_cols if data[col].nunique()<=10}
nn_nuniq_10less

{'night_pck_user_6': 2,
 'night_pck_user_7': 2,
 'night_pck_user_8': 2,
 'night_pck_user_9': 2,
 'fb_user_6': 2,
 'fb_user_7': 2,
 'fb_user_8': 2,
 'fb_user_9': 2}

In [24]:
cat_cols = [col for col in non_null_cols if data[col].dtype == object]
print(cat_cols)

['date_of_last_rech_6', 'date_of_last_rech_7', 'date_of_last_rech_8', 'date_of_last_rech_9', 'date_of_last_rech_data_6', 'date_of_last_rech_data_7', 'date_of_last_rech_data_8', 'date_of_last_rech_data_9']

In [25]:
print("Count of non null continous columns: ",len(non_null_cols)-len(nn_nuniq_10less.keys())-len(cat_cols))

Count of non null continous columns:  136

In [26]:
last_rech_date_cols = ["date_of_last_rech_"+str(i) for i in range(6,10)]
print(last_rech_date_cols)

['date_of_last_rech_6', 'date_of_last_rech_7', 'date_of_last_rech_8', 'date_of_last_rech_9']

In [27]:
# we can make group of 12 columns and make a combined plot for them
cont_cols = [i for i in non_null_cols if i not in cat_cols and i not in last_rech_date_cols and i not in nn_nuniq_10less.keys()]
print(len(cont_cols))
chunk_size = 9   # 9 plots per figure
group_cols = [cont_cols[i:i+chunk_size] for i in range(0, len(cont_cols), chunk_size)]
print(group_cols[0])

136
['onnet_mou_6', 'onnet_mou_7', 'onnet_mou_8', 'onnet_mou_9', 'offnet_mou_6', 'offnet_mou_7', 'offnet_mou_8', 'offnet_mou_9', 'roam_ic_mou_6']

In [28]:
# making grouped kde-plots
# creating the subfolder for kde plot
kde_plots_dir = os.path.join(univar_dir,"KDE_Plots")
os.makedirs(kde_plots_dir, exist_ok = True)
print(f"Directory created: {kde_plots_dir}")

rows, cols = 3, 3
for i, group in enumerate(group_cols):
    fig, axes = plt.subplots(rows, cols, figsize=(18, 18))
    axes = axes.flatten()
    for j, col in enumerate(group):
        sns.kdeplot(data=data, x=col, fill=True, ax=axes[j])
        mean_val = data[col].mean()
        median_val = data[col].median()
        mode_val = data[col].mode().iloc[0]
        # Add vertical lines
        axes[j].axvline(mean_val, color="red", linestyle="--", label=f"Mean = {mean_val:.2f}")
        axes[j].axvline(median_val, color="blue", linestyle="--", label=f"Median = {median_val:.2f}")
        axes[j].axvline(mode_val, color="green", linestyle="--", label=f"Mode = {mode_val:.2f}")
        # Add legend (inside each subplot)
        axes[j].legend(fontsize=9)
        # Title with column name
        axes[j].set_title(col)
    # Hide unused axes if last group < 9
    for k in range(len(group), len(axes)):
        axes[k].set_visible(False)
    plt.suptitle(f"KDE Plots - Group {i+1}", fontsize=22)
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    # Save figure
    fig_path = os.path.join(kde_plots_dir, f"KDE_Group_{i+1}.png")
    plt.savefig(fig_path)
    print(f"KDE_Group_{i+1} saved...")
    plt.close(fig)   # Close to free memory

print(f"All KDE plots saved in: {kde_plots_dir}")

Directory created: d:\Doccuments\GitHub\End-to-End-MLOps-Platform\notebooks\Telecom_Churn_Data\plots\univariate_plots\KDE_Plots
KDE_Group_1 saved...
KDE_Group_2 saved...
KDE_Group_3 saved...
KDE_Group_4 saved...
KDE_Group_5 saved...
KDE_Group_6 saved...
KDE_Group_7 saved...
KDE_Group_8 saved...
KDE_Group_9 saved...
KDE_Group_10 saved...
KDE_Group_11 saved...
KDE_Group_12 saved...
KDE_Group_13 saved...
KDE_Group_14 saved...
KDE_Group_15 saved...
KDE_Group_16 saved...
All KDE plots saved in: d:\Doccuments\GitHub\End-to-End-MLOps-Platform\notebooks\Telecom_Churn_Data\plots\univariate_plots\KDE_Plots

In [29]:
# making dir and plots for categorical columns
# cerating barplot dir
bar_plots_dir = os.path.join(univar_dir,"Bar_Plots")
os.makedirs(bar_plots_dir, exist_ok = True)
print(f"Directory created: {bar_plots_dir}")

rows, cols = 3, 3
group_cols = [cat_cols[i:i+chunk_size] for i in range(0, len(cat_cols), chunk_size)]

# --- Plotting Barplots ---
for i, group in enumerate(group_cols):
    fig, axes = plt.subplots(rows, cols, figsize=(18, 18))
    axes = axes.flatten()
    
    for j, col in enumerate(group):
        # Count the unique values in the categorical column
        value_counts = data[col].value_counts()
        
        # Plot the bar plot for categorical column
        sns.barplot(x=value_counts.index, y=value_counts.values, ax=axes[j], palette="Set2")
        
        # Title and labels
        axes[j].set_title(f"{col}")
        axes[j].set_xlabel(col)
        axes[j].set_ylabel("Count")
        
        # Rotate x-ticks for better readability
        for label in axes[j].get_xticklabels():
            label.set_rotation(45)
        
    # Hide unused axes if the last group has less than 9 categories
    for k in range(len(group), len(axes)):
        axes[k].set_visible(False)
    
    plt.suptitle(f"Categorical Bar Plots - Group {i+1}", fontsize=18)
    plt.tight_layout(rect=[0, 0, 1, 0.95])
    
    # Save the figure to the directory
    fig_path = os.path.join(bar_plots_dir, f"Cat_Group_{i+1}.png")
    plt.savefig(fig_path)
    plt.close(fig)   # Close to free memory

print(f"All categorical bar plots saved in: {bar_plots_dir}")

Directory created: d:\Doccuments\GitHub\End-to-End-MLOps-Platform\notebooks\Telecom_Churn_Data\plots\univariate_plots\Bar_Plots

C:\Users\HP\AppData\Local\Temp\ipykernel_20364\1944011994.py:20: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(x=value_counts.index, y=value_counts.values, ax=axes[j], palette="Set2")
C:\Users\HP\AppData\Local\Temp\ipykernel_20364\1944011994.py:20: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(x=value_counts.index, y=value_counts.values, ax=axes[j], palette="Set2")
C:\Users\HP\AppData\Local\Temp\ipykernel_20364\1944011994.py:20: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(x=value_counts.index, y=value_counts.values, ax=axes[j], palette="Set2")
C:\Users\HP\AppData\Local\Temp\ipykernel_20364\1944011994.py:20: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(x=value_counts.index, y=value_counts.values, ax=axes[j], palette="Set2")
C:\Users\HP\AppData\Local\Temp\ipykernel_20364\1944011994.py:20: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(x=value_counts.index, y=value_counts.values, ax=axes[j], palette="Set2")
C:\Users\HP\AppData\Local\Temp\ipykernel_20364\1944011994.py:20: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(x=value_counts.index, y=value_counts.values, ax=axes[j], palette="Set2")
C:\Users\HP\AppData\Local\Temp\ipykernel_20364\1944011994.py:20: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(x=value_counts.index, y=value_counts.values, ax=axes[j], palette="Set2")
C:\Users\HP\AppData\Local\Temp\ipykernel_20364\1944011994.py:20: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

  sns.barplot(x=value_counts.index, y=value_counts.values, ax=axes[j], palette="Set2")

All categorical bar plots saved in: d:\Doccuments\GitHub\End-to-End-MLOps-Platform\notebooks\Telecom_Churn_Data\plots\univariate_plots\Bar_Plots

In [32]:
cat_cols[4]

'date_of_last_rech_data_6'

In [35]:
data[cat_cols[0]].head(),data[cat_cols[4]].head()

(0    6/21/2014
 1    6/29/2014
 2    6/17/2014
 3    6/28/2014
 4    6/26/2014
 Name: date_of_last_rech_6, dtype: object,
 0    6/21/2014
 1          NaN
 2          NaN
 3          NaN
 4     6/4/2014
 Name: date_of_last_rech_data_6, dtype: object)

### Bivariate Analysis

In [20]:
# bivar_dir = os.path.join(plots_dir, "bivariate_plots")

# os.makedirs(bivar_dir, exist_ok = True)
# print(f"Directory created: {bivar_dir}")